version: '3.9'

services:
 lightyear:
   build: .
   image: lightyear:latest
   container_name: lightyear
   #ports:
   #  - "8080:${PORT:-8080}"
   environment:
     LIGHTYEAR_CLIENT: akeneo
   #  GOOGLE_APPLICATION_CREDENTIALS: /root/keys/keyfile.json
   #volumes:
   #  - ${GCP_KEY_PATH}:/root/keys/keyfile.json:ro
